import WalletContextProvider from "@/components/providers";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppBar from "./_components/appbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Solana Ping!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-50`}>
        <WalletContextProvider>
          <AppBar />
          {children}
        </WalletContextProvider>
      </body>
    </html>
  );
}
